"""change_field

Revision ID: 723e0c7b8dab
Revises: 
Create Date: 2023-06-24 21:48:46.416036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723e0c7b8dab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('url_map', 'short',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('url_map', 'short',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###
